## Part - 1 

Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Data Preprocessing

In [3]:
df = pd.read_csv('Churn_Modelling.csv')
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [4]:
print (X)
#X has 'Geography' and 'Gender' 

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


## Encoding  of Categorical Data

Label Encoding of Gender - in 3rd column of X

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[: ,2] = le.fit_transform(X[:, 2])

OneHotEncoding on 'Geographical' - in 2nd column of X

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer( transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array (ct.fit_transform(X))

In [7]:
print (X)
#X is encoded

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Feature Scaling 
- is Must for NN
- always done after splitting to prevent info leakage

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 101)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train  = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


## Part - 2.

Building the ANN

In [11]:
#Initializing the ANN
ann = tf.keras.models.Sequential()
#Adding Hidden layer - 1 
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))
#Adding Hidden layer - 2
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))
#Adding Output layer - activation - 'sigmoid'(for binary o/p), 'softmax'(for categorical classification i.e more than 2 o/p)
ann.add(tf.keras.layers.Dense(units = 1, activation= 'sigmoid'))


Training the ANN

In [13]:
#compliling - optimizer - 'adam'(stochastic), loss = 'binary_crossentropy'(0/1 op), 'categorical_crossentropy'(categorical classification)
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
#training
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 552us/step - loss: 0.5250 - accuracy: 0.7983
Epoch 2/100
250/250 [==============================] - 0s 558us/step - loss: 0.4831 - accuracy: 0.7983
Epoch 3/100
250/250 [==============================] - 0s 539us/step - loss: 0.4622 - accuracy: 0.7983
Epoch 4/100
250/250 [==============================] - 0s 521us/step - loss: 0.4490 - accuracy: 0.7983
Epoch 5/100
250/250 [==============================] - 0s 517us/step - loss: 0.4391 - accuracy: 0.7983
Epoch 6/100
250/250 [==============================] - 0s 538us/step - loss: 0.4320 - accuracy: 0.7983
Epoch 7/100
250/250 [==============================] - 0s 527us/step - loss: 0.4275 - accuracy: 0.8073
Epoch 8/100
250/250 [==============================] - 0s 515us/step - loss: 0.4243 - accuracy: 0.8189
Epoch 9/100
250/250 [==============================] - 0s 527us/step - loss: 0.4214 - accuracy: 0.8210
Epoch 10/100
250/250 [==============================] - 0s 520us/step - l

##Part - 4

Making Predictions

 - Geography - France
 - Credit Score - 600
 - Gender - Male
 - Age - 40
 - Tenure - 3
 - Balance - 60000
 - Number of Products - 2
 - Does this customer have credit card - Yes
 - Is this customer an active member - Yes
 - Salary - 50000


In [15]:
#note 3 points:
#remember [[]] for prediction
#give encoded value for categorical variables
#transform the feature scaling
print (ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5) # >0.5 is given as a threshold to get output as 0 / 1 i.e True/False

[[False]]


Preicting Test Set

In [17]:
y_pred = ann.predict(X_test) #the o/p is received as probabilities
y_pred = y_pred > 0.5 #to get the result as 0 / 1

Confusion matrix and Accuracy

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print ('Confusion Matrix:')
print (cm)
accu = accuracy_score(y_test, y_pred)
print ('Accuracy score:', accu)

Confusion Matrix:
[[1523   54]
 [ 266  157]]
Accuracy score: 0.84
