## Part - 1

Import Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

Load Dataset - Combined Cycle Power Plant Data Set (taken from UCI repo)

In [6]:
df = pd.read_excel('Folds5x2_pp.xlsx')
df.head()
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

Train Test Split

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 101 )

In [4]:
print (X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print (y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


## Part - 2

Building the ANN

In [8]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1)) #no activatio fn at o/p layer when we are predicting continuous values.

Compile and Train the ANN

In [10]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')
ann.fit(X_train, y_train, epochs = 100, batch_size = 32)

Epoch 1/100
240/240 [==============================] - 0s 783us/step - loss: 423.4030
Epoch 2/100
240/240 [==============================] - 0s 825us/step - loss: 194.2739
Epoch 3/100
240/240 [==============================] - 0s 758us/step - loss: 124.1433
Epoch 4/100
240/240 [==============================] - 0s 738us/step - loss: 74.7549
Epoch 5/100
240/240 [==============================] - 0s 740us/step - loss: 48.3962
Epoch 6/100
240/240 [==============================] - 0s 752us/step - loss: 35.3312
Epoch 7/100
240/240 [==============================] - 0s 732us/step - loss: 30.8715
Epoch 8/100
240/240 [==============================] - 0s 747us/step - loss: 30.0666
Epoch 9/100
240/240 [==============================] - 0s 730us/step - loss: 29.0444
Epoch 10/100
240/240 [==============================] - 0s 735us/step - loss: 28.2858
Epoch 11/100
240/240 [==============================] - 0s 759us/step - loss: 29.5566
Epoch 12/100
240/240 [==============================] - 0s 7

Prediction

In [12]:
y_pred = ann.predict(X_test)

Evaluation Metric: r2_score

In [15]:
from sklearn.metrics import r2_score
r = r2_score(y_test, y_pred)
print ('R^2 Score:', r)


R^2 Score: 0.8977005078193914


We have a good R^2 score!